# Generated by Django 2.1.5 on 2020-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='img',
            field=models.ImageField(default='img/defu.png', upload_to='post_img/'),
        ),
    ]
