# Generated by Django 2.1.5 on 2020-04-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20200408_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_cat',
            name='cat_main',
            field=models.ForeignKey(blank=True, limit_choices_to={'cat_main__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_category_set', to='ads.car_cat'),
        ),
    ]
