# Generated by Django 2.1.5 on 2020-04-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20200408_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='mop_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=15)),
                ('cat_main', models.ForeignKey(blank=True, limit_choices_to={'cat_main__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_category_set', to='ads.mop_cat')),
            ],
        ),
    ]
