# Generated by Django 2.1.5 on 2020-04-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_mop_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.car_cat')),
                ('mop_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.mop_cat')),
            ],
        ),
    ]
