# Generated by Django 2.1.5 on 2020-04-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='catugry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cat_desc', models.TextField()),
                ('Sub', models.ForeignKey(blank=True, limit_choices_to={'Sub__isnull': True, 'main__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_sub_category_set', to='ads.catugry')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_category_set', to='ads.catugry')),
            ],
            options={
                'verbose_name': 'catugry',
                'verbose_name_plural': 'catsdugry',
            },
        ),
        migrations.RemoveField(
            model_name='car_cat',
            name='cat_main',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='car_cat',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='mop_cat',
        ),
        migrations.RemoveField(
            model_name='mop_cat',
            name='cat_main',
        ),
        migrations.DeleteModel(
            name='car_cat',
        ),
        migrations.DeleteModel(
            name='cat',
        ),
        migrations.DeleteModel(
            name='mop_cat',
        ),
        migrations.AddField(
            model_name='ads',
            name='ad_catugr',
            field=models.ForeignKey(limit_choices_to={'Sub__isnull': True, 'main__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.catugry'),
        ),
    ]
