# Generated by Django 2.1.5 on 2020-04-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_auto_20200409_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catugry',
            name='Sub',
        ),
        migrations.AddField(
            model_name='catugry',
            name='sub',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'main__isnull': False, 'sub__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_sub_category_set', to='ads.catugry'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_catugr',
            field=models.ForeignKey(limit_choices_to={'main__isnull': False, 'sub__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.catugry'),
        ),
        migrations.AlterField(
            model_name='catugry',
            name='cat_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catugry',
            name='main',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_category_set', to='ads.catugry'),
        ),
    ]
