# Generated by Django 2.1.5 on 2020-04-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20200409_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catugry',
            name='main',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_category_set', to='ads.catugry'),
        ),
        migrations.AlterField(
            model_name='catugry',
            name='sub',
            field=models.ForeignKey(blank=True, default=' ', limit_choices_to={'main__isnull': False, 'sub__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_sub_category_set', to='ads.catugry'),
        ),
    ]
