# Generated by Django 2.1.5 on 2020-04-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_auto_20200409_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catugry',
            name='cat_desc',
        ),
        migrations.AddField(
            model_name='catugry',
            name='end',
            field=models.ForeignKey(blank=True, limit_choices_to={'main__isnull': False, 'sub__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_end_category_set', to='ads.catugry'),
        ),
        migrations.AlterField(
            model_name='catugry',
            name='main',
            field=models.ForeignKey(blank=True, limit_choices_to={'end__isnull': True, 'main__isnull': True, 'sub__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_category_set', to='ads.catugry'),
        ),
        migrations.AlterField(
            model_name='catugry',
            name='sub',
            field=models.ForeignKey(blank=True, limit_choices_to={'end__isnull': True, 'main__isnull': False, 'sub__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_sub_category_set', to='ads.catugry'),
        ),
    ]
