# Generated by Django 2.1.5 on 2020-04-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_auto_20200409_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='end',
            new_name='ads_end',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='main',
            new_name='ads_main',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='sub',
            new_name='ads_sub',
        ),
    ]
