# Generated by Django 2.1.5 on 2020-04-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_auto_20200409_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='ads_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='ads_main',
            new_name='main',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='ads_sub',
            new_name='sub',
        ),
    ]
