# Generated by Django 3.0.4 on 2020-04-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_auto_20200409_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='ads',
            name='last',
            field=models.ForeignKey(blank=True, limit_choices_to={'end__isnull': False, 'main__isnull': False, 'sub__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_last', to='ads.catugry'),
        ),
    ]
