# Generated by Django 3.0.4 on 2020-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_car_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_form',
            name='payment_option',
            field=models.CharField(choices=[(1, 'Cash'), (2, 'Exchange'), (3, 'Installments')], default='Cash', max_length=1),
        ),
    ]
