# Generated by Django 3.0.4 on 2020-04-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_car_form_payment_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catugry',
            options={'verbose_name': 'catugry', 'verbose_name_plural': 'catugry'},
        ),
        migrations.AddField(
            model_name='car_form',
            name='color',
            field=models.CharField(blank=True, choices=[(1, 'Red'), (2, 'White '), (3, 'Silver '), (4, 'Black '), (5, 'Dark Blue'), (6, 'Dark Gray'), (7, 'Dark Green'), (8, 'Light Brown'), (9, 'Gold '), (10, 'Bright Red')], default='White', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='car_form',
            name='year',
            field=models.CharField(blank=True, choices=[(1, '2001'), (2, '2002'), (3, '2003'), (4, '2004'), (5, '2005'), (6, '2006'), (7, '2007'), (8, '2008'), (9, '2009'), (10, '2010'), (11, '2011'), (12, '2012'), (13, '2013'), (14, '2014'), (15, '2015'), (16, '2016'), (17, '2017'), (18, '2018'), (19, '2019'), (20, '2020')], default='2020', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='car_form',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads'),
        ),
        migrations.AlterField(
            model_name='car_form',
            name='payment_option',
            field=models.CharField(blank=True, choices=[(1, 'Cash'), (2, 'Exchange'), (3, 'Installments')], default='Cash', max_length=1, null=True),
        ),
    ]
