# Generated by Django 3.0.4 on 2020-04-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_auto_20200420_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_form',
            name='Kilometers',
            field=models.CharField(blank=True, choices=[(1, '0 - 999'), (2, '1000 - 29999 '), (3, '30000 - 49999'), (4, '50000 - 99999'), (5, '100000 - 149999'), (5, '150000 - 199999'), (6, 'More Than 200000')], default='0 - 999s', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='car_form',
            name='body_type',
            field=models.CharField(blank=True, choices=[(1, 'SUV'), (2, 'Sedan'), (3, 'Cabriolet'), (4, 'coupe'), (5, 'Hatchback'), (6, 'Pickup'), (7, 'Bus'), (8, 'Other')], default='SUV', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='car_form',
            name='engine_capacity',
            field=models.CharField(blank=True, choices=[(1, '0 - 800'), (2, '1000 - 1300 '), (3, '1400 - 1600'), (4, '1800 - 2000'), (5, '2200 - 2800'), (6, 'More Than 3000')], default='0 - 800', max_length=1, null=True),
        ),
    ]
