# Generated by Django 3.0.4 on 2020-04-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_auto_20200420_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_form',
            old_name='ad',
            new_name='ad_id',
        ),
    ]
