# Generated by Django 3.0.4 on 2020-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_auto_20200420_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_form',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
