# Generated by Django 3.0.4 on 2020-04-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0030_auto_20200420_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_duration', models.CharField(blank=True, choices=[('1', 'Daily'), ('2', 'Monthly'), ('3', 'Yearly')], default='Daily', max_length=1, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rent_option', models.CharField(blank=True, choices=[('1', 'With Driver'), ('2', 'Without Driver'), ('3', 'Both Options')], default='With Driver', max_length=1, null=True)),
                ('year', models.CharField(blank=True, choices=[('1', '2001'), ('2', '2002'), ('3', '2003'), ('4', '2004'), ('5', '2005'), ('6', '2006'), ('7', '2007'), ('8', '2008'), ('9', '2009'), ('10', '2010'), ('11', '2011'), ('12', '2012'), ('13', '2013'), ('14', '2014'), ('15', '2015'), ('16', '2016'), ('17', '2017'), ('18', '2018'), ('19', '2019'), ('20', '2020')], default='2020', max_length=2, null=True)),
                ('color', models.CharField(blank=True, choices=[('1', 'Red'), ('2', 'White '), ('3', 'Silver '), ('4', 'Black '), ('5', 'Dark Blue'), ('6', 'Dark Gray'), ('7', 'Dark Green'), ('8', 'Light Brown'), ('9', 'Gold '), ('10', 'Bright Red')], default='White', max_length=2, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('1', 'SUV'), ('2', 'Sedan'), ('3', 'Cabriolet'), ('4', 'coupe'), ('5', 'Hatchback'), ('6', 'Pickup'), ('7', 'Bus'), ('8', 'Other')], default='SUV', max_length=1, null=True)),
                ('engine_capacity', models.CharField(blank=True, choices=[('1', '0 - 800'), ('2', '1000 - 1300 '), ('3', '1400 - 1600'), ('4', '1800 - 2000'), ('5', '2200 - 2800'), ('6', 'More Than 3000')], default='0 - 800', max_length=1, null=True)),
                ('transmission_type', models.CharField(blank=True, choices=[('1', 'Automatic'), ('2', 'Manual')], default='Manual', max_length=1, null=True)),
                ('abs', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('airbags', models.BooleanField(default=False)),
                ('alarm_System', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('aux_qudio_in', models.BooleanField(default=False)),
                ('bluetooth_system', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('edb', models.BooleanField(default=False)),
                ('fog_lights', models.BooleanField(default=False)),
                ('keyless_start', models.BooleanField(default=False)),
                ('leather_seats', models.BooleanField(default=False)),
                ('navigation_system', models.BooleanField(default=False)),
                ('off_Road_tyres', models.BooleanField(default=False)),
                ('parkings_ensors', models.BooleanField(default=False)),
                ('power_locks', models.BooleanField(default=False)),
                ('power_mirrors', models.BooleanField(default=False)),
                ('power_seats', models.BooleanField(default=False)),
                ('power_steering', models.BooleanField(default=False)),
                ('power_windows', models.BooleanField(default=False)),
                ('premium_wheels_rims', models.BooleanField(default=False)),
                ('rear_view_camera', models.BooleanField(default=False)),
                ('roof_rack', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('touch_screen', models.BooleanField(default=False)),
                ('usb_charger', models.BooleanField(default=False)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
    ]
