# Generated by Django 3.0.4 on 2020-04-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_car_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_rent',
            name='body_type',
            field=models.CharField(blank=True, choices=[('1', 'SUV'), ('2', 'Sedan'), ('3', 'Cabriolet'), ('4', 'coupe'), ('5', 'Hatchback'), ('6', 'Pickup'), ('7', 'Bus'), ('8', 'Other')], default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='color',
            field=models.CharField(blank=True, choices=[('1', 'Red'), ('2', 'White '), ('3', 'Silver '), ('4', 'Black '), ('5', 'Dark Blue'), ('6', 'Dark Gray'), ('7', 'Dark Green'), ('8', 'Light Brown'), ('9', 'Gold '), ('10', 'Bright Red')], default=' ', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '2001'), ('2', '2002'), ('3', '2003'), ('4', '2004'), ('5', '2005'), ('6', '2006'), ('7', '2007'), ('8', '2008'), ('9', '2009'), ('10', '2010'), ('11', '2011'), ('12', '2012'), ('13', '2013'), ('14', '2014'), ('15', '2015'), ('16', '2016'), ('17', '2017'), ('18', '2018'), ('19', '2019'), ('20', '2020')], default=' ', max_length=2, null=True),
        ),
    ]
