# Generated by Django 3.0.4 on 2020-04-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0035_auto_20200420_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catugry',
            name='end',
            field=models.ForeignKey(blank=True, limit_choices_to={'end__isnull': True, 'main__isnull': False, 'sub__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_end', to='ads.catugry'),
        ),
    ]
