# Generated by Django 2.1.5 on 2020-05-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0038_auto_20200424_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=2, null=True)),
                ('condition', models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='car_spare_parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=2, null=True)),
                ('condition', models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='heavy_trucks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=2, null=True)),
                ('condition', models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True)),
                ('year', models.CharField(blank=True, choices=[('1', '2001'), ('2', '2002'), ('3', '2003'), ('4', '2004'), ('5', '2005'), ('6', '2006'), ('7', '2007'), ('8', '2008'), ('9', '2009'), ('10', '2010'), ('11', '2011'), ('12', '2012'), ('13', '2013'), ('14', '2014'), ('15', '2015'), ('16', '2016'), ('17', '2017'), ('18', '2018'), ('19', '2019'), ('20', '2020')], max_length=2, null=True)),
                ('color', models.CharField(blank=True, choices=[('1', 'Red'), ('2', 'White '), ('3', 'Silver '), ('4', 'Black '), ('5', 'Dark Blue'), ('6', 'Dark Gray'), ('7', 'Dark Green'), ('8', 'Light Brown'), ('9', 'Gold '), ('10', 'Bright Red')], max_length=2, null=True)),
                ('engine_capacity', models.CharField(blank=True, choices=[('1', '0 - 800'), ('2', '1000 - 1300 '), ('3', '1400 - 1600'), ('4', '1800 - 2000'), ('5', '2200 - 2800'), ('6', 'More Than 3000')], max_length=1, null=True)),
                ('Kilometers', models.CharField(blank=True, choices=[('1', '0 - 999'), ('2', '1000 - 29999 '), ('3', '30000 - 49999'), ('4', '50000 - 99999'), ('5', '100000 - 149999'), ('5', '150000 - 199999'), ('6', 'More Than 200000')], max_length=1, null=True)),
                ('transmission_type', models.CharField(blank=True, choices=[('1', 'Automatic'), ('2', 'Manual')], max_length=1, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='mobile_accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=2, null=True)),
                ('warranty', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'NO')], max_length=2, null=True)),
                ('condition', models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True)),
                ('color', models.CharField(blank=True, choices=[('1', 'Red'), ('2', 'White '), ('3', 'Silver '), ('4', 'Black '), ('5', 'Dark Blue'), ('6', 'Dark Gray'), ('7', 'Dark Green'), ('8', 'Light Brown'), ('9', 'Gold '), ('10', 'Bright Red')], max_length=2, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='mobile_phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=2, null=True)),
                ('warranty', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'NO')], max_length=2, null=True)),
                ('condition', models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True)),
                ('color', models.CharField(blank=True, choices=[('1', 'Red'), ('2', 'White '), ('3', 'Silver '), ('4', 'Black '), ('5', 'Dark Blue'), ('6', 'Dark Gray'), ('7', 'Dark Green'), ('8', 'Light Brown'), ('9', 'Gold '), ('10', 'Bright Red')], max_length=2, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='motorcycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=2, null=True)),
                ('condition', models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True)),
                ('year', models.CharField(blank=True, choices=[('1', '2001'), ('2', '2002'), ('3', '2003'), ('4', '2004'), ('5', '2005'), ('6', '2006'), ('7', '2007'), ('8', '2008'), ('9', '2009'), ('10', '2010'), ('11', '2011'), ('12', '2012'), ('13', '2013'), ('14', '2014'), ('15', '2015'), ('16', '2016'), ('17', '2017'), ('18', '2018'), ('19', '2019'), ('20', '2020')], max_length=2, null=True)),
                ('color', models.CharField(blank=True, choices=[('1', 'Red'), ('2', 'White '), ('3', 'Silver '), ('4', 'Black '), ('5', 'Dark Blue'), ('6', 'Dark Gray'), ('7', 'Dark Green'), ('8', 'Light Brown'), ('9', 'Gold '), ('10', 'Bright Red')], max_length=2, null=True)),
                ('engine_capacity', models.CharField(blank=True, choices=[('1', '0 - 800'), ('2', '1000 - 1300 '), ('3', '1400 - 1600'), ('4', '1800 - 2000'), ('5', '2200 - 2800'), ('6', 'More Than 3000')], max_length=1, null=True)),
                ('Kilometers', models.CharField(blank=True, choices=[('1', '0 - 999'), ('2', '1000 - 29999 '), ('3', '30000 - 49999'), ('4', '50000 - 99999'), ('5', '100000 - 149999'), ('5', '150000 - 199999'), ('6', 'More Than 200000')], max_length=1, null=True)),
                ('transmission_type', models.CharField(blank=True, choices=[('1', 'Automatic'), ('2', 'Manual')], max_length=1, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.AddField(
            model_name='car_form',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='car_form',
            name='condition',
            field=models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='car_rent',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='car_rent',
            name='condition',
            field=models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='car_form',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True),
        ),
    ]
