# Generated by Django 2.1.5 on 2020-05-31 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0039_auto_20200530_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='car_form',
            new_name='car',
        ),
    ]
