# Generated by Django 2.1.5 on 2020-05-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0040_auto_20200601_0032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boats',
            new_name='db_Boats',
        ),
        migrations.RenameModel(
            old_name='car',
            new_name='db_car',
        ),
        migrations.RenameModel(
            old_name='car_rent',
            new_name='db_car_rent',
        ),
        migrations.RenameModel(
            old_name='car_spare_parts',
            new_name='db_car_spare_parts',
        ),
        migrations.RenameModel(
            old_name='heavy_trucks',
            new_name='db_heavy_trucks',
        ),
        migrations.RenameModel(
            old_name='mobile_phones',
            new_name='db_mobile_accessories',
        ),
        migrations.RenameModel(
            old_name='mobile_accessories',
            new_name='db_mobile_phones',
        ),
        migrations.RenameModel(
            old_name='motorcycles',
            new_name='db_motorcycles',
        ),
    ]
