# Generated by Django 2.1.5 on 2020-06-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0041_auto_20200601_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_furnisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Adoption')], max_length=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female')], max_length=2, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=1, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='db_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('condition', models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=1, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='db_jops_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female')], max_length=1, null=True)),
                ('education', models.CharField(blank=True, choices=[('1', 'Student'), ('2', 'High-Secondary School '), ('3', 'Diploma'), ('4', 'Bachelors Degree'), ('5', 'Masters Degree'), ('5', 'PhD Degree')], max_length=1, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=1, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('1', 'Full-time'), ('2', 'Part-time'), ('3', 'Internship'), ('3', 'Freelance')], max_length=1, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='db_properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=1, null=True)),
                ('for_sale_rent', models.CharField(blank=True, choices=[('1', 'Sale'), ('2', 'rent')], max_length=1, null=True)),
                ('level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('bedrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('bathrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Area (m²) ')),
                ('furnished', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'NO')], max_length=1, null=True)),
                ('Compound', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'NO')], max_length=1, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('private_Garden', models.BooleanField(default=False)),
                ('central_ac_heating', models.BooleanField(default=False)),
                ('water_Meter', models.BooleanField(default=False)),
                ('natural_Gas', models.BooleanField(default=False)),
                ('electricity_Meter', models.BooleanField(default=False)),
                ('covered_Parking', models.BooleanField(default=False)),
                ('maids_Room', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('landline', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='db_properties_buildings_lands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=1, null=True)),
                ('for_sale_rent', models.CharField(blank=True, choices=[('1', 'Sale'), ('2', 'rent')], max_length=1, null=True)),
                ('level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('bedrooms_in_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('bathrooms_in_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Area (m²) ')),
                ('Compound', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'NO')], max_length=1, null=True)),
                ('central_ac_heating', models.BooleanField(default=False)),
                ('water_Meter', models.BooleanField(default=False)),
                ('natural_Gas', models.BooleanField(default=False)),
                ('electricity_Meter', models.BooleanField(default=False)),
                ('covered_Parking', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('landline', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='db_properties_ecommer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=1, null=True)),
                ('for_sale_rent', models.CharField(blank=True, choices=[('1', 'Sale'), ('2', 'rent')], max_length=1, null=True)),
                ('level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('bedrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('bathrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '+11')], max_length=2, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Area (m²) ')),
                ('furnished', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'NO')], max_length=1, null=True)),
                ('Compound', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'NO')], max_length=1, null=True)),
                ('central_ac_heating', models.BooleanField(default=False)),
                ('water_Meter', models.BooleanField(default=False)),
                ('natural_Gas', models.BooleanField(default=False)),
                ('electricity_Meter', models.BooleanField(default=False)),
                ('covered_Parking', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('landline', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.RenameField(
            model_name='db_boats',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='db_car',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='db_car_rent',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='db_car_spare_parts',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='db_heavy_trucks',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='db_mobile_accessories',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='db_mobile_phones',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='db_motorcycles',
            old_name='Price',
            new_name='price',
        ),
    ]
