# Generated by Django 2.1.5 on 2020-06-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0042_auto_20200609_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Adoption')], max_length=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female')], max_length=2, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('1', 'For Sale'), ('2', 'Wanted item')], max_length=1, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True)),
                ('ad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
        migrations.RemoveField(
            model_name='db_furnisher',
            name='age',
        ),
        migrations.RemoveField(
            model_name='db_furnisher',
            name='gender',
        ),
        migrations.AddField(
            model_name='db_furnisher',
            name='condition',
            field=models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Used')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='db_furnisher',
            name='room_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Area (m²) '),
        ),
        migrations.AlterField(
            model_name='db_furnisher',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Exchange'), ('3', 'Installments'), ('4', 'Rent')], max_length=1, null=True),
        ),
    ]
