# Generated by Django 2.1.5 on 2020-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0043_auto_20200609_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_jops_services',
            name='Salary',
        ),
        migrations.AddField(
            model_name='db_jops_services',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Salary'),
        ),
    ]
