# Generated by Django 2.1.5 on 2020-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0045_auto_20200611_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_jops_services',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='db_pets',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
