# Generated by Django 2.1.5 on 2020-06-17 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='governorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate_name', models.CharField(blank=True, choices=[('1', 'Beheira'), ('2', 'Asyut'), ('3', 'Damietta'), ('4', 'Kafr El Sheikh'), ('5', 'Beni Suef'), ('6', 'New Valley'), ('7', 'Dakahlia'), ('8', 'Ismailia'), ('9', 'Cairo'), ('10', 'Faiyum'), ('11', 'North Sinai'), ('12', 'Luxor'), ('13', 'Giza'), ('14', 'Gharbia'), ('15', 'Port Said'), ('16', 'Matruh'), ('17', 'Minya'), ('18', 'Monufia'), ('19', 'Qalyubia'), ('20', 'Qena'), ('21', 'Red Sea'), ('22', 'Sharqia'), ('23', 'Sohag'), ('24', 'South Sinai'), ('25', 'Suez'), ('26', 'Aswan'), ('27', 'Alexandria')], max_length=2, null=True)),
                ('center_city', models.ForeignKey(blank=True, limit_choices_to={'governorate_name__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center', to='user_profile.governorate')),
            ],
        ),
    ]
