# Generated by Django 2.1.5 on 2020-06-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200617_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
