# Generated by Django 2.1.5 on 2020-06-17 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0046_auto_20200611_1648'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0008_auto_20200617_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField(default=1114796307)),
                ('favoret_ads', models.ManyToManyField(to='ads.ads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
