# Generated by Django 2.1.5 on 2020-06-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='messages_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
