# Generated by Django 3.2.6 on 2021-08-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20200617_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
